### ISSUE TITLE
Add a small html webpage with some list

### ISSUE THREAD

**Issue by cheerans650** [cheerans650/ProgrammingTheList#1]

**Comment by at-rm** [comment]
Hi, I'd love to contribute. What should be displayed in the list? Is there anything else you want on your page? :)

**Comment by cheerans650** [comment]
> Hi, I'd love to contribute. What should be displayed in the list? Is there anything else you want on your page? :)

Sorry , I was teaching my friend to use github, Sorry for thr trouble
